services:
  database:
    image: postgres:17
    container_name: postgres_contenedor
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tu_password_aqui  
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432" 
    volumes:
      
      - ./backup_proyecto.sql:/docker-entrypoint-initdb.d/init.sql
      
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: